# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
      time: "19:00"
      timezone: Europe/Berlin
    # Raise pull requests for version updates
    # to gomod against the `staging` branch
    target-branch: "staging"
    # Disable rebasing pull requests
    rebase-strategy: "auto"
    # Allow up to 10 open pull requests
    open-pull-requests-limit: 10
    # Labels on pull requests for version updates only
    labels:
      - "dependabot"
      - "gomod"
    assignees: [ Synertry ]
    reviewers: [ Synertry ]
    commit-message:
      prefix: "Go Modules"
      include: "scope"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "19:00"
      timezone: Europe/Berlin
    target-branch: "staging"
    rebase-strategy: "auto"
    open-pull-requests-limit: 10
    labels:
      - "dependabot"
      - "gomod"
    assignees: [ Synertry ]
    reviewers: [ Synertry ]
    commit-message:
      prefix: "GitHub Actions"
      include: "scope"