version = 1

test_patterns = [
  "Daily/**/*_test.go"
]

exclude_patterns = [
  "main.go"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/Synertry/RushDevsDailyGo"
  skip_doc_coverage = ["main.go"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[transformers]]
name = "gofmt"
enabled = true

[[transformers]]
name = "prettier"
enabled = true