name: Sync Develop

on:
  push:
    branches: [ main ]

env:
  GOPROXY: https://proxy.golang.org
  GO111MODULE: on

# Cancel any in-progress CI runs for a PR if it is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  sync-dev:
    name: Syncing branch from staging to develop # Just commits the push on staging back into develop
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    needs: review-code
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
        with:
          ref: staging

      - name: Push commit back
        run: git push origin staging:develop